your:
  datasource:
    host: localhost
    port: 3306
    database: myDB
    username: root
    password: 753951JcJ~
    stat-view-servlet:
      login-username: admin
      login-password: 123456
  redis:
    host: localhost
    port: 6379
    database: 2
    #    cluster:
    #      #使用逗号分隔开
    #      nodes: localhost:7000,localhost:7001,localhost:7002
  alioss:
    access-key-id: XXX
    access-key-secret: XXX
    bucket-name: XXX
    endpoint: XXX
  jwt:
    #仅在管理端使用
    admin-secret-key: admin
    admin-ttl: 7200000
    admin-token-name: token

    user-secret-key: myJwt
    user-ttl: 7200000
    user-token-name: authentication
knife4j:
  basic:
    enable: true
    username: admin
    password: 123456



