your:
  datasource:
    host: localhost
    port: 3306
    database: myDB
    username: root
    password: 123456
    stat-view-servlet:
      login-username: admin
      login-password: 123456
  redis:
    host: localhost
    port: 6379
    database: 2
#    cluster:
#      #使用逗号分隔开
#      nodes: localhost:7000,localhost:7001,localhost:7002
knife4j:
  basic:
    enable: true
    username: admin
    password: 123456



